name: meta_wearables
description: "Wearables Device Access Toolkit SDK for Flutter."
version: 0.0.1
homepage: https://chunkytofustudios.com
repository: https://github.com/ChunkyTofuStudios/meta_wearables

environment:
  sdk: ^3.7.2
  flutter: ">=3.29.3"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  pigeon: ^26.1.4

flutter:
  plugin:
    platforms:
      android:
        package: com.chunkytofustudios.meta_wearables.meta_wearables
        pluginClass: MetaWearablesPlugin
      ios:
        pluginClass: MetaWearablesPlugin
